name: Build Libs

on:
  workflow_call:
    inputs:
      github_sha:
        required: true
        type: string
    secrets:
      repo_token:
        required: true
      domain_owner:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ inputs.github_sha }}
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.repo_token }}

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
      
      - id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Build
        run: |
          aws codeartifact get-authorization-token --domain pypi-springlabs --domain-owner ${{ secrets.domain_owner }} --query authorizationToken --output text --debug
          make pypi-generate
          ./infrastructure/tools/tag_generation_gh.sh
          make pypi-push
